apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: ope-test
  labels:
    app: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          args:
            - "--web.listen-address=:9091"
          ports:
            - containerPort: 9091
              name: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: ope-test
  labels:
    app: pushgateway
spec:
  selector:
    app: pushgateway
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  type: ClusterIP